export { HingeProvider, useHinge, useHingeRegions, useHingeSnapshot, useHingeController } from './HingeProvider';
export type { HingeProviderProps } from './HingeProvider';
export { createHingeController } from './store';
export type { HingeController } from './store';
export type { HingeInfo, HingeStatus, HingeRegion, HingeSnapshot, HingeUnavailableReason } from './types';
export { HingeProvider as FoldableProvider, useFoldable, useDisplayFeatures, useFoldablePosture, useHingeController as useFoldableController } from './HingeProvider';
export type { HingeProviderProps as FoldableProviderProps } from './HingeProvider';
export { createHingeController as createFoldableController } from './store';
export type { HingeController as FoldableController } from './store';
export { getFoldablePanes, getFoldableLayoutMode } from './foldable';
export type { FoldableRect, FoldablePosture, FoldableSnapshot, DisplayFeature } from './foldable';
export { useFoldableScreen } from './HingeProvider';
export { getFoldableScreen } from './screen';
export type { FoldableScreen, FoldableScreenInfo, FoldableScreenOptions } from './screen';
